---
title: "GO analysis"
author: "Koen van der Burg"
date: "19/05/2021"
output: html_document
editor_options: 
chunk_output_type: inline
---
  
# GO Analysis
  
## Setup library

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r loading library, echo = FALSE, include=FALSE, message=FALSE, warning=FALSE}

library(clusterProfiler)
library(enrichplot)
library(ggplot2)

install.packages("R.utils")
R.utils::setOption("clusterProfiler.download.method","auto")

# we use ggplot2 to add x axis labels (ex: ridgeplot)

#ET THE DESIRED ORGANISM HERE
organism = "org.Hs.eg.db"
BiocManager::install(organism, character.only = TRUE)
library(organism, character.only = TRUE)

```

```{r loading dataframe and prepare input, echo = FALSE, include = FALSE}
sig_down <- read.table("sigIHW_down.csv", header = TRUE)
sig_down <- data.frame(sig_down, row.names = sig_down$gene_id)                  #Set row_names -> sample names
sig_down <- subset(sig_down, select = -(gene_id))                               #Removal total column
write.csv(sig_down,sep="\t", quote=F, col.names=NA, file.path("C:/Users/koenv/OneDrive/Documenten/Universiteit/Bio-informatica Jaar 3/Thesis/Innsbruck_project/Analysis", "sigIHW_down_2.csv"))
sig_down <- read.csv("sigIHW_down_2.csv", header = TRUE)


original_gene_list <- sig_down$log2FoldChange                                          
names(original_gene_list) <- sig_down$X                                 # name the vector
gene_list<-na.omit(original_gene_list)                                          # omit any NA values 
gene_list = sort(gene_list, decreasing = TRUE)                                  # sort the list in decreasing order (required for clusterProfiler)

```

```{r Gene set Enrichtment, echo= FALSE, include= FALSE}

gse <- gseGO(geneList=gene_list, 
             ont ="ALL", 
             keyType = "ENSEMBL", 
             nPerm = 10000, 
             minGSSize = 3, 
             maxGSSize = 800, 
             pvalueCutoff = 0.05, 
             verbose = TRUE, 
             OrgDb = org.Hs.eg.db, 
             pAdjustMethod = "none")

```

```{r Dotplot, warning = FALSE, message= FALSE}


require(DOSE)
dotplot(gse, showCategory=10, split=".sign") + facet_grid(.~.sign)
``` 

```{r Enrichment Map, warning= FALSE, message = FALSE}
cnetplot(gse, categorySize="pvalue", foldChange=gene_list, showCategory = 3)
ridgeplot(gse) + labs(x = "enrichment distribution")


compare_cluster_GO_emap <- enrichplot::pairwise_termsim(gse, semData = gse)
emapplot(compare_cluster_GO_emap, showCategory = 10)



```





```{r Prepare input KEGG, echo= FALSE, include=FALSE}
# Convert gene IDs for gseKEGG function
# We will lose some genes here because not all IDs will be converted
ids<-bitr(names(original_gene_list), fromType = "ENSEMBL", toType = "ENTREZID", OrgDb= "org.Hs.eg.db")
 # remove duplicate IDS (here I use "ENSEMBL", but it should be whatever was selected as keyType)
dedup_ids = ids[!duplicated(ids[c("ENSEMBL")]),]

# Create a new dataframe df2 which has only the genes which were successfully mapped using the bitr function above
df2 = sig_down[sig_down$X %in% dedup_ids$ENSEMBL,]

# Create a new column in df2 with the corresponding ENTREZ IDs
df2$Y = dedup_ids$ENTREZID

# Create a vector of the gene unuiverse
kegg_gene_list <- df2$log2FoldChange

# Name vector with ENTREZ ids
names(kegg_gene_list) <- df2$Y

# omit any NA values 
kegg_gene_list<-na.omit(kegg_gene_list)

# sort the list in decreasing order (required for clusterProfiler)
kegg_gene_list = sort(kegg_gene_list, decreasing = TRUE)

```

```{r Create gseKEGG object, echo=FALSE, include=FALSE}
kk2 <- gseKEGG(geneList     = kegg_gene_list,
               organism     = "hsa",
               nPerm        = 10000,
               minGSSize    = 0,
               maxGSSize    = 800,
               pvalueCutoff = 0.5,
               pAdjustMethod = "none",
               keyType       = "ncbi-geneid")
```

```{r Dotplot, warning= FALSE, message= FALSE}
cnetplot(kk2, categorySize="pvalue", foldChange=gene_list)

compare_cluster_GO_KEGG <- enrichplot::pairwise_termsim(kk2, semData = kk2)
emapplot(compare_cluster_GO_KEGG, showCategory = 10)

dotplot(kk2, showCategory = 10, title = "Enriched Pathways" , split=".sign") + facet_grid(.~.sign)

```